version: "3.2"
services:
  converter-api:
    image: gcr.io/cloud-uniandes/converter-api-image
    container_name: 'converter-api'
    build:
      context: ./converter
      dockerfile: api.Dockerfile
    working_dir: /backend/
    env_file:
      - db.env
      - converter/app.env
      - converter/events.env
    command: sh api.sh
    ports:
      - "9080:${PORT:-5000}"
    environment:
      PORT: ${PORT:-5000}

  converter-async:
    image: gcr.io/cloud-uniandes/converter-async-image
    container_name: 'converter-async'
    build:
      context: ./converter
      dockerfile: events.Dockerfile
    working_dir: /backend/
    environment:
      PYTHONUNBUFFERED: 1
      PORT: ${PORT:-5001}
    env_file:
      - db.env
      - converter/events.env
    command: sh events.sh
    ports:
      - "9090:${PORT:-5001}"